export const siteConfig = {
  url: 'https://rsla.io',
  name: 'RSL/A',
  alternateName: ['RSLA', 'RSL/A', 'RSL A', 'RSL/A Agency'],
  tagline: 'The trusted AI growth partner for B2B companies',
  description: 'RSL/A builds AI growth systems for B2B companies. Website, search visibility, AI automations, CRM, and reporting, all connected.',
  founder: {
    name: 'Rahul Lalia',
    jobTitle: 'Founder & CEO',
    url: 'https://rsla.io/about',
    linkedin: 'https://www.linkedin.com/in/rahullalia/',
    sameAs: [
      'https://www.linkedin.com/in/rahullalia/',
      'https://www.youtube.com/@rahul_lalia',
      'https://www.tiktok.com/@rahul_lalia',
      'https://x.com/rahul_lalia',
      'https://github.com/rahullalia',
    ],
  },
  email: 'hello@rsla.io',
  address: {
    street: '',
    city: 'Bakersfield',
    state: 'CA',
    zip: '93301',
    region: 'Kern County',
    country: 'US',
  },
  geo: {
    latitude: 35.3733,
    longitude: -119.0187,
  },
  social: {
    linkedin: 'https://www.linkedin.com/in/rahullalia/',
    instagram: 'https://www.instagram.com/rahul.lalia/',
    youtube: 'https://www.youtube.com/@rahul_lalia',
    tiktok: 'https://www.tiktok.com/@rahul_lalia',
    x: 'https://x.com/rahul_lalia',
    github: 'https://github.com/rahullalia',
  },
  logo: {
    url: 'https://rsla.io/images/logo/lockup-nobg.webp',
    width: 400,
    height: 100,
  },
  knowsAbout: [
    'AI Automation',
    'Web Development',
    'Search Engine Optimization',
    'Answer Engine Optimization',
    'GoHighLevel CRM',
    'Marketing Automation',
    'Local SEO',
    'Google Business Profile',
    'Content Marketing',
    'Claude Code',
  ],
  services: [
    { name: 'Web Design', slug: 'web-design' },
    { name: 'SEO', slug: 'seo' },
    { name: 'AI Automations', slug: 'ai-automations' },
    { name: 'CRM Systems', slug: 'crm-systems' },
    { name: 'Custom Development', slug: 'custom-development' },
  ],
};
